"""few changes and new tables genres and profil

Revision ID: 092da10c057f
Revises: 19a0d6a1a59f
Create Date: 2024-06-20 11:51:12.352196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '092da10c057f'
down_revision: Union[str, None] = '19a0d6a1a59f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_genres_id'), 'genres', ['id'], unique=False)
    op.create_table('profils',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('genre_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'genre_id')
                    )

    # Add pseudoname with a default value
    op.add_column('users', sa.Column('pseudoname', sa.String(), nullable=False, server_default='default_pseudoname'))

    # Remove server default if not needed anymore
    op.alter_column('users', 'pseudoname', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pseudoname')
    op.drop_table('profils')
    op.drop_index(op.f('ix_genres_id'), table_name='genres')
    op.drop_table('genres')
    # ### end Alembic commands ###
