"""add new column

Revision ID: 7e83be572956
Revises:
Create Date: 2024-05-21 17:15:20.545916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e83be572956'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profils',
    sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),  # Added 'id' column
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Integer(), nullable=False),
    )
    op.create_index(op.f('ix_profils_id'), 'profils', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profils_id'), table_name='profils')
    op.drop_table('profils')
    # ### end Alembic commands ###
