"""Ajout de tables users et musics

Revision ID: 8e84a2b7826b
Revises: 9b3a1d71be05
Create Date: 2024-05-27 17:31:18.087080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e84a2b7826b'
down_revision: Union[str, None] = '9b3a1d71be05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('musics',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('artist', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_musics_id'), 'musics', ['id'], unique=False)
    op.create_index(op.f('ix_musics_title'), 'musics', ['title'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('user_music',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('music_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['music_id'], ['musics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'music_id', 'id')
    )
    op.create_index(op.f('ix_user_music_id'), 'user_music', ['id'], unique=False)
    op.drop_index('ix_profils_id', table_name='profils')
    op.drop_table('profils')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profils',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='profils_pkey')
    )
    op.create_index('ix_profils_id', 'profils', ['id'], unique=False)
    op.drop_index(op.f('ix_user_music_id'), table_name='user_music')
    op.drop_table('user_music')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_musics_title'), table_name='musics')
    op.drop_index(op.f('ix_musics_id'), table_name='musics')
    op.drop_table('musics')
    # ### end Alembic commands ###
