"""fourth test

Revision ID: 9b3a1d71be05
Revises: a51af9eebfff
Create Date: 2024-05-22 16:15:10.293968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b3a1d71be05'
down_revision: Union[str, None] = 'a51af9eebfff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profils',
    sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),  # Added 'id' column
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Integer(), nullable=False),
    )
    op.create_index(op.f('ix_profils_id'), 'profils', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profils_id'), table_name='profils')
    op.drop_table('profils')
    # ### end Alembic commands ###